version: '3'

services:
  web:
    build: ./app
    ports:
      - "9090:9000"
    volumes:
      - ./app:/var/www
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: car_reviews
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./nginx  # Build the Nginx container from the "nginx" directory
    ports:
      - "8080:80"
    links:
      - web
