version: '3'

services:

  app:
    build: .
    ports:
      - '9001:9000'
    volumes:
      - .:/app:cached

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=car_reviews
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=

  nginx:
    image: nginx:stable
    ports:
      - '8088:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app