<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRDplOkj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRDplOkj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRDplOkj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRDplOkj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRDplOkj\App_KernelDevDebugContainer([
    'container.build_hash' => 'RDplOkj',
    'container.build_id' => 'cf7eb831',
    'container.build_time' => 1698828056,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRDplOkj');
